// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"code.cloudfoundry.org/cf-k8s-api/apis"
	"code.cloudfoundry.org/cf-k8s-api/repositories"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type CFPackageRepository struct {
	CreatePackageStub        func(context.Context, client.Client, repositories.PackageCreate) (repositories.PackageRecord, error)
	createPackageMutex       sync.RWMutex
	createPackageArgsForCall []struct {
		arg1 context.Context
		arg2 client.Client
		arg3 repositories.PackageCreate
	}
	createPackageReturns struct {
		result1 repositories.PackageRecord
		result2 error
	}
	createPackageReturnsOnCall map[int]struct {
		result1 repositories.PackageRecord
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CFPackageRepository) CreatePackage(arg1 context.Context, arg2 client.Client, arg3 repositories.PackageCreate) (repositories.PackageRecord, error) {
	fake.createPackageMutex.Lock()
	ret, specificReturn := fake.createPackageReturnsOnCall[len(fake.createPackageArgsForCall)]
	fake.createPackageArgsForCall = append(fake.createPackageArgsForCall, struct {
		arg1 context.Context
		arg2 client.Client
		arg3 repositories.PackageCreate
	}{arg1, arg2, arg3})
	stub := fake.CreatePackageStub
	fakeReturns := fake.createPackageReturns
	fake.recordInvocation("CreatePackage", []interface{}{arg1, arg2, arg3})
	fake.createPackageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CFPackageRepository) CreatePackageCallCount() int {
	fake.createPackageMutex.RLock()
	defer fake.createPackageMutex.RUnlock()
	return len(fake.createPackageArgsForCall)
}

func (fake *CFPackageRepository) CreatePackageCalls(stub func(context.Context, client.Client, repositories.PackageCreate) (repositories.PackageRecord, error)) {
	fake.createPackageMutex.Lock()
	defer fake.createPackageMutex.Unlock()
	fake.CreatePackageStub = stub
}

func (fake *CFPackageRepository) CreatePackageArgsForCall(i int) (context.Context, client.Client, repositories.PackageCreate) {
	fake.createPackageMutex.RLock()
	defer fake.createPackageMutex.RUnlock()
	argsForCall := fake.createPackageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CFPackageRepository) CreatePackageReturns(result1 repositories.PackageRecord, result2 error) {
	fake.createPackageMutex.Lock()
	defer fake.createPackageMutex.Unlock()
	fake.CreatePackageStub = nil
	fake.createPackageReturns = struct {
		result1 repositories.PackageRecord
		result2 error
	}{result1, result2}
}

func (fake *CFPackageRepository) CreatePackageReturnsOnCall(i int, result1 repositories.PackageRecord, result2 error) {
	fake.createPackageMutex.Lock()
	defer fake.createPackageMutex.Unlock()
	fake.CreatePackageStub = nil
	if fake.createPackageReturnsOnCall == nil {
		fake.createPackageReturnsOnCall = make(map[int]struct {
			result1 repositories.PackageRecord
			result2 error
		})
	}
	fake.createPackageReturnsOnCall[i] = struct {
		result1 repositories.PackageRecord
		result2 error
	}{result1, result2}
}

func (fake *CFPackageRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createPackageMutex.RLock()
	defer fake.createPackageMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CFPackageRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ apis.CFPackageRepository = new(CFPackageRepository)
