---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korifi-knative-runner-appworkload-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - appworkloads
  - runnerinfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - appworkloads/status
  - runnerinfos/status
  verbs:
  - get
  - patch
