// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"code.cloudfoundry.org/korifi/api/authorization"
	apis "code.cloudfoundry.org/korifi/api/handlers"
	"code.cloudfoundry.org/korifi/api/repositories"
)

type CFProcessRepository struct {
	GetProcessStub        func(context.Context, authorization.Info, string) (repositories.ProcessRecord, error)
	getProcessMutex       sync.RWMutex
	getProcessArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 string
	}
	getProcessReturns struct {
		result1 repositories.ProcessRecord
		result2 error
	}
	getProcessReturnsOnCall map[int]struct {
		result1 repositories.ProcessRecord
		result2 error
	}
	GetProcessByAppTypeAndSpaceStub        func(context.Context, authorization.Info, string, string, string) (repositories.ProcessRecord, error)
	getProcessByAppTypeAndSpaceMutex       sync.RWMutex
	getProcessByAppTypeAndSpaceArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 string
		arg4 string
		arg5 string
	}
	getProcessByAppTypeAndSpaceReturns struct {
		result1 repositories.ProcessRecord
		result2 error
	}
	getProcessByAppTypeAndSpaceReturnsOnCall map[int]struct {
		result1 repositories.ProcessRecord
		result2 error
	}
	ListProcessesStub        func(context.Context, authorization.Info, repositories.ListProcessesMessage) ([]repositories.ProcessRecord, error)
	listProcessesMutex       sync.RWMutex
	listProcessesArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.ListProcessesMessage
	}
	listProcessesReturns struct {
		result1 []repositories.ProcessRecord
		result2 error
	}
	listProcessesReturnsOnCall map[int]struct {
		result1 []repositories.ProcessRecord
		result2 error
	}
	PatchProcessStub        func(context.Context, authorization.Info, repositories.PatchProcessMessage) (repositories.ProcessRecord, error)
	patchProcessMutex       sync.RWMutex
	patchProcessArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.PatchProcessMessage
	}
	patchProcessReturns struct {
		result1 repositories.ProcessRecord
		result2 error
	}
	patchProcessReturnsOnCall map[int]struct {
		result1 repositories.ProcessRecord
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CFProcessRepository) GetProcess(arg1 context.Context, arg2 authorization.Info, arg3 string) (repositories.ProcessRecord, error) {
	fake.getProcessMutex.Lock()
	ret, specificReturn := fake.getProcessReturnsOnCall[len(fake.getProcessArgsForCall)]
	fake.getProcessArgsForCall = append(fake.getProcessArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetProcessStub
	fakeReturns := fake.getProcessReturns
	fake.recordInvocation("GetProcess", []interface{}{arg1, arg2, arg3})
	fake.getProcessMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CFProcessRepository) GetProcessCallCount() int {
	fake.getProcessMutex.RLock()
	defer fake.getProcessMutex.RUnlock()
	return len(fake.getProcessArgsForCall)
}

func (fake *CFProcessRepository) GetProcessCalls(stub func(context.Context, authorization.Info, string) (repositories.ProcessRecord, error)) {
	fake.getProcessMutex.Lock()
	defer fake.getProcessMutex.Unlock()
	fake.GetProcessStub = stub
}

func (fake *CFProcessRepository) GetProcessArgsForCall(i int) (context.Context, authorization.Info, string) {
	fake.getProcessMutex.RLock()
	defer fake.getProcessMutex.RUnlock()
	argsForCall := fake.getProcessArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CFProcessRepository) GetProcessReturns(result1 repositories.ProcessRecord, result2 error) {
	fake.getProcessMutex.Lock()
	defer fake.getProcessMutex.Unlock()
	fake.GetProcessStub = nil
	fake.getProcessReturns = struct {
		result1 repositories.ProcessRecord
		result2 error
	}{result1, result2}
}

func (fake *CFProcessRepository) GetProcessReturnsOnCall(i int, result1 repositories.ProcessRecord, result2 error) {
	fake.getProcessMutex.Lock()
	defer fake.getProcessMutex.Unlock()
	fake.GetProcessStub = nil
	if fake.getProcessReturnsOnCall == nil {
		fake.getProcessReturnsOnCall = make(map[int]struct {
			result1 repositories.ProcessRecord
			result2 error
		})
	}
	fake.getProcessReturnsOnCall[i] = struct {
		result1 repositories.ProcessRecord
		result2 error
	}{result1, result2}
}

func (fake *CFProcessRepository) GetProcessByAppTypeAndSpace(arg1 context.Context, arg2 authorization.Info, arg3 string, arg4 string, arg5 string) (repositories.ProcessRecord, error) {
	fake.getProcessByAppTypeAndSpaceMutex.Lock()
	ret, specificReturn := fake.getProcessByAppTypeAndSpaceReturnsOnCall[len(fake.getProcessByAppTypeAndSpaceArgsForCall)]
	fake.getProcessByAppTypeAndSpaceArgsForCall = append(fake.getProcessByAppTypeAndSpaceArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.GetProcessByAppTypeAndSpaceStub
	fakeReturns := fake.getProcessByAppTypeAndSpaceReturns
	fake.recordInvocation("GetProcessByAppTypeAndSpace", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.getProcessByAppTypeAndSpaceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CFProcessRepository) GetProcessByAppTypeAndSpaceCallCount() int {
	fake.getProcessByAppTypeAndSpaceMutex.RLock()
	defer fake.getProcessByAppTypeAndSpaceMutex.RUnlock()
	return len(fake.getProcessByAppTypeAndSpaceArgsForCall)
}

func (fake *CFProcessRepository) GetProcessByAppTypeAndSpaceCalls(stub func(context.Context, authorization.Info, string, string, string) (repositories.ProcessRecord, error)) {
	fake.getProcessByAppTypeAndSpaceMutex.Lock()
	defer fake.getProcessByAppTypeAndSpaceMutex.Unlock()
	fake.GetProcessByAppTypeAndSpaceStub = stub
}

func (fake *CFProcessRepository) GetProcessByAppTypeAndSpaceArgsForCall(i int) (context.Context, authorization.Info, string, string, string) {
	fake.getProcessByAppTypeAndSpaceMutex.RLock()
	defer fake.getProcessByAppTypeAndSpaceMutex.RUnlock()
	argsForCall := fake.getProcessByAppTypeAndSpaceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *CFProcessRepository) GetProcessByAppTypeAndSpaceReturns(result1 repositories.ProcessRecord, result2 error) {
	fake.getProcessByAppTypeAndSpaceMutex.Lock()
	defer fake.getProcessByAppTypeAndSpaceMutex.Unlock()
	fake.GetProcessByAppTypeAndSpaceStub = nil
	fake.getProcessByAppTypeAndSpaceReturns = struct {
		result1 repositories.ProcessRecord
		result2 error
	}{result1, result2}
}

func (fake *CFProcessRepository) GetProcessByAppTypeAndSpaceReturnsOnCall(i int, result1 repositories.ProcessRecord, result2 error) {
	fake.getProcessByAppTypeAndSpaceMutex.Lock()
	defer fake.getProcessByAppTypeAndSpaceMutex.Unlock()
	fake.GetProcessByAppTypeAndSpaceStub = nil
	if fake.getProcessByAppTypeAndSpaceReturnsOnCall == nil {
		fake.getProcessByAppTypeAndSpaceReturnsOnCall = make(map[int]struct {
			result1 repositories.ProcessRecord
			result2 error
		})
	}
	fake.getProcessByAppTypeAndSpaceReturnsOnCall[i] = struct {
		result1 repositories.ProcessRecord
		result2 error
	}{result1, result2}
}

func (fake *CFProcessRepository) ListProcesses(arg1 context.Context, arg2 authorization.Info, arg3 repositories.ListProcessesMessage) ([]repositories.ProcessRecord, error) {
	fake.listProcessesMutex.Lock()
	ret, specificReturn := fake.listProcessesReturnsOnCall[len(fake.listProcessesArgsForCall)]
	fake.listProcessesArgsForCall = append(fake.listProcessesArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.ListProcessesMessage
	}{arg1, arg2, arg3})
	stub := fake.ListProcessesStub
	fakeReturns := fake.listProcessesReturns
	fake.recordInvocation("ListProcesses", []interface{}{arg1, arg2, arg3})
	fake.listProcessesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CFProcessRepository) ListProcessesCallCount() int {
	fake.listProcessesMutex.RLock()
	defer fake.listProcessesMutex.RUnlock()
	return len(fake.listProcessesArgsForCall)
}

func (fake *CFProcessRepository) ListProcessesCalls(stub func(context.Context, authorization.Info, repositories.ListProcessesMessage) ([]repositories.ProcessRecord, error)) {
	fake.listProcessesMutex.Lock()
	defer fake.listProcessesMutex.Unlock()
	fake.ListProcessesStub = stub
}

func (fake *CFProcessRepository) ListProcessesArgsForCall(i int) (context.Context, authorization.Info, repositories.ListProcessesMessage) {
	fake.listProcessesMutex.RLock()
	defer fake.listProcessesMutex.RUnlock()
	argsForCall := fake.listProcessesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CFProcessRepository) ListProcessesReturns(result1 []repositories.ProcessRecord, result2 error) {
	fake.listProcessesMutex.Lock()
	defer fake.listProcessesMutex.Unlock()
	fake.ListProcessesStub = nil
	fake.listProcessesReturns = struct {
		result1 []repositories.ProcessRecord
		result2 error
	}{result1, result2}
}

func (fake *CFProcessRepository) ListProcessesReturnsOnCall(i int, result1 []repositories.ProcessRecord, result2 error) {
	fake.listProcessesMutex.Lock()
	defer fake.listProcessesMutex.Unlock()
	fake.ListProcessesStub = nil
	if fake.listProcessesReturnsOnCall == nil {
		fake.listProcessesReturnsOnCall = make(map[int]struct {
			result1 []repositories.ProcessRecord
			result2 error
		})
	}
	fake.listProcessesReturnsOnCall[i] = struct {
		result1 []repositories.ProcessRecord
		result2 error
	}{result1, result2}
}

func (fake *CFProcessRepository) PatchProcess(arg1 context.Context, arg2 authorization.Info, arg3 repositories.PatchProcessMessage) (repositories.ProcessRecord, error) {
	fake.patchProcessMutex.Lock()
	ret, specificReturn := fake.patchProcessReturnsOnCall[len(fake.patchProcessArgsForCall)]
	fake.patchProcessArgsForCall = append(fake.patchProcessArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.PatchProcessMessage
	}{arg1, arg2, arg3})
	stub := fake.PatchProcessStub
	fakeReturns := fake.patchProcessReturns
	fake.recordInvocation("PatchProcess", []interface{}{arg1, arg2, arg3})
	fake.patchProcessMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CFProcessRepository) PatchProcessCallCount() int {
	fake.patchProcessMutex.RLock()
	defer fake.patchProcessMutex.RUnlock()
	return len(fake.patchProcessArgsForCall)
}

func (fake *CFProcessRepository) PatchProcessCalls(stub func(context.Context, authorization.Info, repositories.PatchProcessMessage) (repositories.ProcessRecord, error)) {
	fake.patchProcessMutex.Lock()
	defer fake.patchProcessMutex.Unlock()
	fake.PatchProcessStub = stub
}

func (fake *CFProcessRepository) PatchProcessArgsForCall(i int) (context.Context, authorization.Info, repositories.PatchProcessMessage) {
	fake.patchProcessMutex.RLock()
	defer fake.patchProcessMutex.RUnlock()
	argsForCall := fake.patchProcessArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CFProcessRepository) PatchProcessReturns(result1 repositories.ProcessRecord, result2 error) {
	fake.patchProcessMutex.Lock()
	defer fake.patchProcessMutex.Unlock()
	fake.PatchProcessStub = nil
	fake.patchProcessReturns = struct {
		result1 repositories.ProcessRecord
		result2 error
	}{result1, result2}
}

func (fake *CFProcessRepository) PatchProcessReturnsOnCall(i int, result1 repositories.ProcessRecord, result2 error) {
	fake.patchProcessMutex.Lock()
	defer fake.patchProcessMutex.Unlock()
	fake.PatchProcessStub = nil
	if fake.patchProcessReturnsOnCall == nil {
		fake.patchProcessReturnsOnCall = make(map[int]struct {
			result1 repositories.ProcessRecord
			result2 error
		})
	}
	fake.patchProcessReturnsOnCall[i] = struct {
		result1 repositories.ProcessRecord
		result2 error
	}{result1, result2}
}

func (fake *CFProcessRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getProcessMutex.RLock()
	defer fake.getProcessMutex.RUnlock()
	fake.getProcessByAppTypeAndSpaceMutex.RLock()
	defer fake.getProcessByAppTypeAndSpaceMutex.RUnlock()
	fake.listProcessesMutex.RLock()
	defer fake.listProcessesMutex.RUnlock()
	fake.patchProcessMutex.RLock()
	defer fake.patchProcessMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CFProcessRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ apis.CFProcessRepository = new(CFProcessRepository)
