apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: korifi-statefulset-runner
  name: korifi-statefulset-runner-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.statefulsetRunner.replicas }}
  selector:
    matchLabels:
      app: korifi-statefulset-runner
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: korifi-statefulset-runner
    spec:
      containers:
      - name: manager
        image: {{ .Values.statefulsetRunner.image }}
{{- if .Values.debug }}
        command:
        - "/dlv"
        args:
        - "--listen=:40000"
        - "--headless=true"
        - "--api-version=2"
        - "exec"
        - "/manager"
        - "--continue"
        - "--accept-multiclient"
        - "--"
        - "--health-probe-bind-address=:8081"
        - "--leader-elect"
{{- else }}
        args:
        - --health-probe-bind-address=:8081
        - --leader-elect
{{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
        {{- .Values.statefulsetRunner.resources | toYaml | nindent 10 }}
        {{- include "korifi.securityContext" . | indent 8 }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      {{- include "korifi.podSecurityContext" . | indent 6 }}
      serviceAccountName: korifi-statefulset-runner-controller-manager
{{- if .Values.statefulsetRunner.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.statefulsetRunner.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.statefulsetRunner.tolerations }}
      tolerations:
      {{- toYaml .Values.statefulsetRunner.tolerations | nindent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ .Values.statefulsetRunner.webhookCertSecret }}
