apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-statefulset-runner-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - korifi-statefulset-runner-webhook-service.{{ .Release.Namespace }}.svc
  - korifi-statefulset-runner-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: korifi-statefulset-runner-webhook-server-cert
