apiVersion: v1
kind: Service
metadata:
  name: korifi-statefulset-runner-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: korifi-statefulset-runner
---
{{- if .Values.debug }}
apiVersion: v1
kind: Service
metadata:
  name: korifi-statefulset-runner-debug-port
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: debug-30055
      nodePort: 30055
      port: 30055
      protocol: TCP
      targetPort: 40000
  selector:
    app: korifi-statefulset-runner
  type: NodePort
{{- end }}
