{{- if .Values.generateWebhookCertificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.statefulsetRunner.webhookCertSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - korifi-statefulset-runner-webhook-service.{{ .Release.Namespace }}.svc
  - korifi-statefulset-runner-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: {{ .Values.statefulsetRunner.webhookCertSecret }}
{{- end}}
