run:
  # increase timeout for cases when tests run in parallel with linters
  timeout: 20m
  # which dirs to skip: they won't be analyzed;
  skip-dirs:
    - vendor
    - pkg
  modules-download-mode: mod

linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true

linters:
  # Maximum issues count per one linter. Set to 0 to disable.
  max-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable
  max-same: 0

  # Show only new issues
  new: false

  enable:
    - dupl
    - ginkgolinter

  disable:
    - staticcheck # we run this separately

issues:
  exclude-rules:
    - path: _test\.go
      linters:
      - dupl
    # We are getting false positives comparing the cfserviceinstance and cfservicebinding reconcile loops. This may
    # become unnecessary later if the implementation diverges more.
    - path: service\w+_controller\.go
      linters:
        - dupl
    # Ignore false positive duplicate linter errors comparing validating webhooks for cforg and cfapp.
    - path: workloads/cf\w+_validation\.go
      linters:
        - dupl
