// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"net/http"
	"sync"

	"code.cloudfoundry.org/cf-k8s-controllers/api/apis"
	"code.cloudfoundry.org/cf-k8s-controllers/api/authorization"
)

type AuthAwareHandlerFunc struct {
	Stub        func(authorization.Info, http.ResponseWriter, *http.Request)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 authorization.Info
		arg2 http.ResponseWriter
		arg3 *http.Request
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AuthAwareHandlerFunc) Spy(arg1 authorization.Info, arg2 http.ResponseWriter, arg3 *http.Request) {
	fake.mutex.Lock()
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 authorization.Info
		arg2 http.ResponseWriter
		arg3 *http.Request
	}{arg1, arg2, arg3})
	stub := fake.Stub
	fake.recordInvocation("AuthAwareHandlerFunc", []interface{}{arg1, arg2, arg3})
	fake.mutex.Unlock()
	if stub != nil {
		fake.Stub(arg1, arg2, arg3)
	}
}

func (fake *AuthAwareHandlerFunc) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *AuthAwareHandlerFunc) Calls(stub func(authorization.Info, http.ResponseWriter, *http.Request)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *AuthAwareHandlerFunc) ArgsForCall(i int) (authorization.Info, http.ResponseWriter, *http.Request) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2, fake.argsForCall[i].arg3
}

func (fake *AuthAwareHandlerFunc) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AuthAwareHandlerFunc) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ apis.AuthAwareHandlerFunc = new(AuthAwareHandlerFunc).Spy
