apiVersion: v1
kind: ServiceAccount
metadata:
  name: korifi-route-controller-manager
  namespace: { { .Release.Namespace } }
  { { - if .Values.eksContainerRegistryRoleARN } }
  annotations:
    eks.amazonaws.com/role-arn: { { .Values.eksContainerRegistryRoleARN } }
  { { - end } }
imagePullSecrets:
  {{- range .Values.systemImagePullSecrets }}
- name: {{ . | quote }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: korifi-route-controller-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: korifi-route-controller-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: korifi-route-controller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: korifi-route-controller-manager
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korifi-route-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korifi-route-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: korifi-route-controller-manager
    namespace: {{ .Release.Namespace }}
