---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korifi-route-controller-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  verbs:
  - get
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfroutes/finalizers
  verbs:
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfroutes/status
  verbs:
  - get
  - patch
  - update
