apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: korifi-job-task-runner
  name: korifi-job-task-runner-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.jobTaskRunner.replicas }}
  selector:
    matchLabels:
      app: korifi-job-task-runner
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: korifi-job-task-runner
    spec:
      containers:
      - name: manager
        image: {{ .Values.jobTaskRunner.image }}
{{- if .Values.debug }}
        command:
        - "/dlv"
        args:
        - "--listen=:40000"
        - "--headless=true"
        - "--api-version=2"
        - "exec"
        - "/manager"
        - "--continue"
        - "--accept-multiclient"
        - "--"
        - "--health-probe-bind-address=:8081"
        - "--leader-elect"
        - "--ttl={{ required "jobTTL is required" .Values.jobTaskRunner.jobTTL }}"
{{- else }}
        args:
        - --health-probe-bind-address=:8081
        - --leader-elect
        - --ttl={{ required "jobTTL is required" .Values.jobTaskRunner.jobTTL }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
        {{- .Values.jobTaskRunner.resources | toYaml | nindent 10 }}
        {{- include "korifi.securityContext" . | indent 8 }}
      {{- include "korifi.podSecurityContext" . | indent 6 }}
      serviceAccountName: korifi-job-task-runner-controller-manager
{{- if .Values.jobTaskRunner.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.jobTaskRunner.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.jobTaskRunner.tolerations }}
      tolerations:
      {{- toYaml .Values.jobTaskRunner.tolerations | nindent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 10
