// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"code.cloudfoundry.org/cf-k8s-controllers/api/authorization"
	"code.cloudfoundry.org/cf-k8s-controllers/api/repositories"
)

type AuthorizedNamespacesProvider struct {
	GetAuthorizedOrgNamespacesStub        func(context.Context, authorization.Info) ([]string, error)
	getAuthorizedOrgNamespacesMutex       sync.RWMutex
	getAuthorizedOrgNamespacesArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
	}
	getAuthorizedOrgNamespacesReturns struct {
		result1 []string
		result2 error
	}
	getAuthorizedOrgNamespacesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	GetAuthorizedSpaceNamespacesStub        func(context.Context, authorization.Info) ([]string, error)
	getAuthorizedSpaceNamespacesMutex       sync.RWMutex
	getAuthorizedSpaceNamespacesArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
	}
	getAuthorizedSpaceNamespacesReturns struct {
		result1 []string
		result2 error
	}
	getAuthorizedSpaceNamespacesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedOrgNamespaces(arg1 context.Context, arg2 authorization.Info) ([]string, error) {
	fake.getAuthorizedOrgNamespacesMutex.Lock()
	ret, specificReturn := fake.getAuthorizedOrgNamespacesReturnsOnCall[len(fake.getAuthorizedOrgNamespacesArgsForCall)]
	fake.getAuthorizedOrgNamespacesArgsForCall = append(fake.getAuthorizedOrgNamespacesArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
	}{arg1, arg2})
	stub := fake.GetAuthorizedOrgNamespacesStub
	fakeReturns := fake.getAuthorizedOrgNamespacesReturns
	fake.recordInvocation("GetAuthorizedOrgNamespaces", []interface{}{arg1, arg2})
	fake.getAuthorizedOrgNamespacesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedOrgNamespacesCallCount() int {
	fake.getAuthorizedOrgNamespacesMutex.RLock()
	defer fake.getAuthorizedOrgNamespacesMutex.RUnlock()
	return len(fake.getAuthorizedOrgNamespacesArgsForCall)
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedOrgNamespacesCalls(stub func(context.Context, authorization.Info) ([]string, error)) {
	fake.getAuthorizedOrgNamespacesMutex.Lock()
	defer fake.getAuthorizedOrgNamespacesMutex.Unlock()
	fake.GetAuthorizedOrgNamespacesStub = stub
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedOrgNamespacesArgsForCall(i int) (context.Context, authorization.Info) {
	fake.getAuthorizedOrgNamespacesMutex.RLock()
	defer fake.getAuthorizedOrgNamespacesMutex.RUnlock()
	argsForCall := fake.getAuthorizedOrgNamespacesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedOrgNamespacesReturns(result1 []string, result2 error) {
	fake.getAuthorizedOrgNamespacesMutex.Lock()
	defer fake.getAuthorizedOrgNamespacesMutex.Unlock()
	fake.GetAuthorizedOrgNamespacesStub = nil
	fake.getAuthorizedOrgNamespacesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedOrgNamespacesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.getAuthorizedOrgNamespacesMutex.Lock()
	defer fake.getAuthorizedOrgNamespacesMutex.Unlock()
	fake.GetAuthorizedOrgNamespacesStub = nil
	if fake.getAuthorizedOrgNamespacesReturnsOnCall == nil {
		fake.getAuthorizedOrgNamespacesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.getAuthorizedOrgNamespacesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedSpaceNamespaces(arg1 context.Context, arg2 authorization.Info) ([]string, error) {
	fake.getAuthorizedSpaceNamespacesMutex.Lock()
	ret, specificReturn := fake.getAuthorizedSpaceNamespacesReturnsOnCall[len(fake.getAuthorizedSpaceNamespacesArgsForCall)]
	fake.getAuthorizedSpaceNamespacesArgsForCall = append(fake.getAuthorizedSpaceNamespacesArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
	}{arg1, arg2})
	stub := fake.GetAuthorizedSpaceNamespacesStub
	fakeReturns := fake.getAuthorizedSpaceNamespacesReturns
	fake.recordInvocation("GetAuthorizedSpaceNamespaces", []interface{}{arg1, arg2})
	fake.getAuthorizedSpaceNamespacesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedSpaceNamespacesCallCount() int {
	fake.getAuthorizedSpaceNamespacesMutex.RLock()
	defer fake.getAuthorizedSpaceNamespacesMutex.RUnlock()
	return len(fake.getAuthorizedSpaceNamespacesArgsForCall)
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedSpaceNamespacesCalls(stub func(context.Context, authorization.Info) ([]string, error)) {
	fake.getAuthorizedSpaceNamespacesMutex.Lock()
	defer fake.getAuthorizedSpaceNamespacesMutex.Unlock()
	fake.GetAuthorizedSpaceNamespacesStub = stub
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedSpaceNamespacesArgsForCall(i int) (context.Context, authorization.Info) {
	fake.getAuthorizedSpaceNamespacesMutex.RLock()
	defer fake.getAuthorizedSpaceNamespacesMutex.RUnlock()
	argsForCall := fake.getAuthorizedSpaceNamespacesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedSpaceNamespacesReturns(result1 []string, result2 error) {
	fake.getAuthorizedSpaceNamespacesMutex.Lock()
	defer fake.getAuthorizedSpaceNamespacesMutex.Unlock()
	fake.GetAuthorizedSpaceNamespacesStub = nil
	fake.getAuthorizedSpaceNamespacesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *AuthorizedNamespacesProvider) GetAuthorizedSpaceNamespacesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.getAuthorizedSpaceNamespacesMutex.Lock()
	defer fake.getAuthorizedSpaceNamespacesMutex.Unlock()
	fake.GetAuthorizedSpaceNamespacesStub = nil
	if fake.getAuthorizedSpaceNamespacesReturnsOnCall == nil {
		fake.getAuthorizedSpaceNamespacesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.getAuthorizedSpaceNamespacesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *AuthorizedNamespacesProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAuthorizedOrgNamespacesMutex.RLock()
	defer fake.getAuthorizedOrgNamespacesMutex.RUnlock()
	fake.getAuthorizedSpaceNamespacesMutex.RLock()
	defer fake.getAuthorizedSpaceNamespacesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AuthorizedNamespacesProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repositories.AuthorizedNamespacesProvider = new(AuthorizedNamespacesProvider)
