// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"io"
	"sync"

	"code.cloudfoundry.org/korifi/api/repositories"
	v1 "k8s.io/api/core/v1"
	"k8s.io/client-go/kubernetes"
)

type LogStreamer struct {
	Stub        func(context.Context, kubernetes.Interface, v1.Pod, v1.PodLogOptions) (io.ReadCloser, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 context.Context
		arg2 kubernetes.Interface
		arg3 v1.Pod
		arg4 v1.PodLogOptions
	}
	returns struct {
		result1 io.ReadCloser
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 io.ReadCloser
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *LogStreamer) Spy(arg1 context.Context, arg2 kubernetes.Interface, arg3 v1.Pod, arg4 v1.PodLogOptions) (io.ReadCloser, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 context.Context
		arg2 kubernetes.Interface
		arg3 v1.Pod
		arg4 v1.PodLogOptions
	}{arg1, arg2, arg3, arg4})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("LogStreamer", []interface{}{arg1, arg2, arg3, arg4})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return returns.result1, returns.result2
}

func (fake *LogStreamer) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *LogStreamer) Calls(stub func(context.Context, kubernetes.Interface, v1.Pod, v1.PodLogOptions) (io.ReadCloser, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *LogStreamer) ArgsForCall(i int) (context.Context, kubernetes.Interface, v1.Pod, v1.PodLogOptions) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2, fake.argsForCall[i].arg3, fake.argsForCall[i].arg4
}

func (fake *LogStreamer) Returns(result1 io.ReadCloser, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 io.ReadCloser
		result2 error
	}{result1, result2}
}

func (fake *LogStreamer) ReturnsOnCall(i int, result1 io.ReadCloser, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 io.ReadCloser
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 io.ReadCloser
		result2 error
	}{result1, result2}
}

func (fake *LogStreamer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *LogStreamer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repositories.LogStreamer = new(LogStreamer).Spy
