// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"code.cloudfoundry.org/cf-k8s-controllers/api/repositories"
	"k8s.io/metrics/pkg/apis/metrics/v1beta1"
)

type MetricsFetcherFn struct {
	Stub        func(context.Context, string, string) (*v1beta1.PodMetrics, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	returns struct {
		result1 *v1beta1.PodMetrics
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 *v1beta1.PodMetrics
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *MetricsFetcherFn) Spy(arg1 context.Context, arg2 string, arg3 string) (*v1beta1.PodMetrics, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("MetricsFetcherFn", []interface{}{arg1, arg2, arg3})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return returns.result1, returns.result2
}

func (fake *MetricsFetcherFn) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *MetricsFetcherFn) Calls(stub func(context.Context, string, string) (*v1beta1.PodMetrics, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *MetricsFetcherFn) ArgsForCall(i int) (context.Context, string, string) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2, fake.argsForCall[i].arg3
}

func (fake *MetricsFetcherFn) Returns(result1 *v1beta1.PodMetrics, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 *v1beta1.PodMetrics
		result2 error
	}{result1, result2}
}

func (fake *MetricsFetcherFn) ReturnsOnCall(i int, result1 *v1beta1.PodMetrics, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 *v1beta1.PodMetrics
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 *v1beta1.PodMetrics
		result2 error
	}{result1, result2}
}

func (fake *MetricsFetcherFn) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MetricsFetcherFn) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repositories.MetricsFetcherFn = new(MetricsFetcherFn).Spy
