{{- if .Values.certManager.include }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-kpack-image-builder-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - korifi-kpack-image-builder-webhook-service.{{ .Release.Namespace }}.svc
  - korifi-kpack-image-builder-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Values.certManager.webhookCertsIssuer }}
  secretName: korifi-kpack-image-builder-webhook-cert
{{- end}}
