apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: korifi-kpack-image-builder
  name: korifi-kpack-image-builder-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.kpackImageBuilder.replicas | default 1}}
  selector:
    matchLabels:
      app: korifi-kpack-image-builder
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        checksum/config: {{ tpl ($.Files.Get "controllers/configmap.yaml") $ | sha256sum }}
      labels:
        app: korifi-kpack-image-builder
    spec:
      containers:
      - name: manager
        image: {{ .Values.kpackImageBuilder.image }}
{{- if .Values.debug }}
        command:
        - "/dlv"
        args:
        - "--listen=:40000"
        - "--headless=true"
        - "--api-version=2"
        - "exec"
        - "/manager"
        - "--continue"
        - "--accept-multiclient"
        - "--"
        - "--health-probe-bind-address=:8081"
        - "--leader-elect"
        - "--config=/etc/korifi-kpack-image-builder-config"
{{- else }}
        args:
        - --health-probe-bind-address=:8081
        - --leader-elect
        - --config=/etc/korifi-kpack-image-builder-config
{{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
        {{- .Values.jobTaskRunner.resources | toYaml | nindent 10 }}
        {{- include "korifi.securityContext" . | indent 8 }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - mountPath: /etc/korifi-kpack-image-builder-config
          name: korifi-kpack-image-builder-config
          readOnly: true
      {{- include "korifi.podSecurityContext" . | indent 6 }}
      serviceAccountName: korifi-kpack-image-builder-controller-manager
{{- if .Values.kpackImageBuilder.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.kpackImageBuilder.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.kpackImageBuilder.tolerations }}
      tolerations:
      {{- toYaml .Values.kpackImageBuilder.tolerations | nindent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ .Values.kpackImageBuilder.webhookCertSecret }}
      - configMap:
          name: korifi-kpack-image-builder-config
        name: korifi-kpack-image-builder-config
