apiVersion: v1
kind: Service
metadata:
  name: korifi-kpack-image-builder-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: korifi-kpack-image-builder
