{{- if .Values.generateInternalCertificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.api.apiServer.internalCertSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: korifi-api-svc.{{ .Release.Namespace }}.svc.cluster.local
  dnsNames:
  - korifi-api-svc.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: {{ .Values.api.apiServer.internalCertSecret }}
{{- end }}
