apiVersion: v1
kind: ServiceAccount
metadata:
  name: korifi-api-system-serviceaccount
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.eksContainerRegistryRoleARN }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.eksContainerRegistryRoleARN }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korifi-api-system-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korifi-api-system-role
subjects:
- kind: ServiceAccount
  name: korifi-api-system-serviceaccount
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: korifi-api-system-rolebinding
  namespace: {{ .Values.global.rootNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: korifi-api-system-role
subjects:
- kind: ServiceAccount
  name: korifi-api-system-serviceaccount
  namespace: {{ .Release.Namespace }}
