apiVersion: v1
kind: Service
metadata:
  labels:
    app: korifi-api
  name: korifi-api-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: web
    port: 443
    protocol: TCP
    targetPort: web
  selector:
    app: korifi-api
  type: ClusterIP
