apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-9999"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: post-upgrade-set-migrated-by-label
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: post-upgrade-set-migrated-by-label
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: korifi-controllers-controller-manager
      restartPolicy: Never
      {{- include "korifi.podSecurityContext" . | indent 6 }}
      containers:
      - name: post-upgrade-set-migrated-by-label
        env:
        - name: KORIFI_VERSION
          value: "{{ .Chart.Version }}"
        image: {{ .Values.helm.hooksImage }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        command:
        - bash
        - -c
        - |
          set-label() {
            local kind namespace name
            kind=$1
            namespace="$2"
            name="$3"
            label="$4"
            label_value="$5"

            kubectl patch \
              --namespace "$namespace" \
              --type=merge \
              --patch "{\"metadata\": {\"labels\" : {\"$label\": \"$label_value\"}}}" \
              "$kind" "$name"
          }

          set-migrated-by-label() {
            local resource_kinds=(cfapps cfdomains)

            for kind in "${resource_kinds[@]}"; do
              resources="$(kubectl get --all-namespaces "$kind" -o=custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name --no-headers)"
              if [[ -z "${resources}" ]]; then
                echo "No resources of kind $kind. Nothing to do."
                continue
              fi

              while IFS= read -r line; do
                read -r namespace name <<<$line
                set-label "$kind" "$namespace" "$name" "korifi.cloudfoundry.org/migrated-by" "$KORIFI_VERSION"
              done <<<"$resources"
            done
          }

          main() {
            set-migrated-by-label
          }

          main
