{{- if or (eq .Values.generateIngressCertificates true) (eq .Values.generateInternalCertificates true) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end}}
