{{- if or (eq .Values.generateIngressCertificates true) (eq .Values.generateInternalCertificates true) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-selfsigned-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  duration: 8760h # 1 year
  secretName: korifi-selfsigned-ca-secret
  commonName: korifi-selfsigned-ca
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: korifi-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: korifi-selfsigned-ca-secret
{{- end}}
