{{- if .Values.certManager.include }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.certManager.webhookCertsIssuer }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end}}
