---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane-service-broker
  namespace: crossplane-service-broker
  labels:
    app.kubernetes.io/instance: crossplane-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: crossplane-services
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: crossplane-services
    spec:
      serviceAccountName: crossplane-service-broker
      containers:
        - name: crossplane-service-broker
          image: $CROSSPLANE_BROKER_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: OSB_NAMESPACE
              value: crossplane-services
            - name: OSB_SERVICE_IDS
              value: $OSB_SERVICE_IDS
            - name: OSB_USERNAME
              value: test
            - name: OSB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crossplane-service-broker
                  key: password
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
