---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crossplane-service-broker
subjects:
  - kind: ServiceAccount
    name: crossplane-service-broker
    namespace: crossplane-service-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-edit
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crossplane-service-broker-createns
subjects:
  - kind: ServiceAccount
    name: crossplane-service-broker
    namespace: crossplane-service-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-service-broker-createns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-service-broker-createns
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
