---
apiVersion: v1
kind: Service
metadata:
  name: crossplane-service-broker
  namespace: crossplane-service-broker
  labels:
    app.kubernetes.io/instance: crossplane-services
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: crossplane-services
  ports:
    - name: http
      port: 80
      targetPort: http
