apiVersion: v1
kind: ConfigMap
metadata:
  name: korifi-gateway-api-router-config
  namespace: {{ .Releases.Namespace }}
data:
  config.yaml: |-
    builderName: {{ .Values.gatewayApiRouter.builderName | default "cf-gateway-api-router-builder" }}
    runnerName: {{ .Values.gatewayApiRouter.runnerName | default "cf-gateway-api-router-runner" }}
    cfRootNamespace: {{ .Values.rootNamespace }}
    namespaceLabels:
    {{ - range $key, $value := .Values.gateway-api-router.namespaceLabels }}
      {{ $key }}: {{ $value }}
    {{ - end }}
    logLevel: { { .Values.logLevel } }