apiVersion: apps/v1
kind: Deployment
metadata:
  name: korifi-gateway-api-router-manager
  labels:
    app: korifi-gateway-api-router
  namespace: { { .Release.Namespace } }
spec:
  replicas: { { .Values.controllers.replicas | default 1 } }
  selector:
    matchLabels:
      app: korifi-gateway-api-router
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        checksum/config: { { tpl ($.Files.Get "gateway-api-router/configmap.yaml") $ | sha256sum } }
      labels:
        app: korifi-gateway-api-router
    spec:
      containers:
        - name: manager
          env:
            - name: ROUTECONTROLCONFIG
              value: /etc/korifi-gateway-api-router-config
          image: { { .Values.gateway-api-router.image } }
          imagePullPolicy: IfNotPresent
          { { - if .Values.debug } }
          command:
            - "/dlv"
          args:
            - "--listen=:40000"
            - "--headless=true"
            - "--api-version=2"
            - "exec"
            - "/manager"
            - "--continue"
            - "--accept-multiclient"
            - "--"
            - "--health-probe-bind-address=:8081"
            - "--leader-elect"
          { { - else } }
          args:
            - "--health-probe-bind-address=:8081"
            - "--leader-elect"
          { { - end } }
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            { { - include "korifi.resources" . | indent 8 } }
            { { - include "korifi.securityContext" . | indent 8 } }
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /etc/korifi-gateway-api-router-config
              name: korifi-gateway-api-router-config
              readOnly: true
            { { - include "korifi.podSecurityContext" . | indent 6 } }
      serviceAccountName: korifi-gateway-api-router-manager
        { {- if .Values.gateway-api-router.nodeSelector }}
      nodeSelector:
        { { toYaml .Values.gateway-api-router.nodeSelector | indent 8 } }
        { { - end } }
        { { - if .Values.gateway-api-router.tolerations } }
      tolerations:
        { { - toYaml .Values.gateway-api-router.tolerations | nindent 8 } }
        { { - end } }
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: gateway-api-router-webhook-server-cert
        - configMap:
            name: korifi-gateway-api-router-config
          name: korifi-gateway-api-router-config