---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: korifi-gateway-api-router-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/korifi-gateway-api-router-serving-cert'
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: korifi-gateway-api-router-webhook-service
        namespace: '{{ .Release.Namespace }}'
        path: /mutate-korifi-cloudfoundry-org-v1alpha1-cfroute
    failurePolicy: Fail
    name: mcfroute.korifi.cloudfoundry.org
    rules:
      - apiGroups:
          - korifi.cloudfoundry.org
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cfroutes
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: korifi-gateway-api-router-webhook-service
        namespace: '{{ .Release.Namespace }}'
        path: /mutate-korifi-cloudfoundry-org-v1alpha1-gateway-api-router-finalizer
    failurePolicy: Fail
    name: mcffinalizer.korifi.cloudfoundry.org
    rules:
      - apiGroups:
          - korifi.cloudfoundry.org
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - cfroutes
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: korifi-gateway-api-router-webhook-service
        namespace: '{{ .Release.Namespace }}'
        path: /mutate-korifi-cloudfoundry-org-v1alpha1-gateway-api-router-space-guid
    failurePolicy: Fail
    name: mcfspaceguid.korifi.cloudfoundry.org
    rules:
      - apiGroups:
          - korifi.cloudfoundry.org
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cfroutes
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: korifi-gateway-api-router-webhook-service
        namespace: '{{ .Release.Namespace }}'
        path: /mutate-korifi-cloudfoundry-org-v1alpha1-all-version
    failurePolicy: Fail
    name: mcfversion.korifi.cloudfoundry.org
    rules:
      - apiGroups:
          - korifi.cloudfoundry.org
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cfroutes
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: korifi-gateway-api-router-webhook-service
        namespace: '{{ .Release.Namespace }}'
        path: /mutate-korifi-cloudfoundry-org-v1alpha1-all-version
    failurePolicy: Fail
    name: mcfversion.korifi.cloudfoundry.org
    rules:
      - apiGroups:
          - gateway.networking.k8s.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - httproutes
          - httproutes/status
    sideEffects: None
