---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: korifi-gateway-api-router-manager
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
{{- range .Values.systemImagePullSecrets }}
- name: {{ . | quote }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: korifi-gateway-api-router-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: korifi-controllers-leader-election-role
subjects:
  - kind: ServiceAccount
    name: korifi-gateway-api-router-manager
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-api-router-admin
subjects:
  - kind: ServiceAccount
    name: korifi-gateway-api-router-manager
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io