// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"code.cloudfoundry.org/korifi/api/repositories"
	"code.cloudfoundry.org/korifi/api/repositories/k8sklient"
	"code.cloudfoundry.org/korifi/api/repositories/k8sklient/descriptors"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type Lister struct {
	ListStub        func(context.Context, schema.GroupVersionKind, repositories.ListOptions) (client.ObjectList, descriptors.PageInfo, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
		arg1 context.Context
		arg2 schema.GroupVersionKind
		arg3 repositories.ListOptions
	}
	listReturns struct {
		result1 client.ObjectList
		result2 descriptors.PageInfo
		result3 error
	}
	listReturnsOnCall map[int]struct {
		result1 client.ObjectList
		result2 descriptors.PageInfo
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Lister) List(arg1 context.Context, arg2 schema.GroupVersionKind, arg3 repositories.ListOptions) (client.ObjectList, descriptors.PageInfo, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
		arg1 context.Context
		arg2 schema.GroupVersionKind
		arg3 repositories.ListOptions
	}{arg1, arg2, arg3})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{arg1, arg2, arg3})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *Lister) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *Lister) ListCalls(stub func(context.Context, schema.GroupVersionKind, repositories.ListOptions) (client.ObjectList, descriptors.PageInfo, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *Lister) ListArgsForCall(i int) (context.Context, schema.GroupVersionKind, repositories.ListOptions) {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	argsForCall := fake.listArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Lister) ListReturns(result1 client.ObjectList, result2 descriptors.PageInfo, result3 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 client.ObjectList
		result2 descriptors.PageInfo
		result3 error
	}{result1, result2, result3}
}

func (fake *Lister) ListReturnsOnCall(i int, result1 client.ObjectList, result2 descriptors.PageInfo, result3 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 client.ObjectList
			result2 descriptors.PageInfo
			result3 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 client.ObjectList
		result2 descriptors.PageInfo
		result3 error
	}{result1, result2, result3}
}

func (fake *Lister) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Lister) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ k8sklient.Lister = new(Lister)
