{{- if .Values.generateIngressCertificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-workloads-ingress-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: \*.{{ .Values.defaultAppDomainName }}
  dnsNames:
  - \*.{{ .Values.defaultAppDomainName }}
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: {{ .Values.controllers.workloadsTLSSecret }}
{{- end}}
