{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.controllers.labelSigningSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controllers.labelSigningSecret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if $existing }}
  key: {{ index $existing.data "key" }}
  {{- else }}
  key: {{ randBytes 32 | b64enc }}
  {{- end }}
