apiVersion: v1
kind: ServiceAccount
metadata:
  name: korifi-controllers-controller-manager
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.eksContainerRegistryRoleARN }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.eksContainerRegistryRoleARN }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: korifi-controllers-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: korifi-controllers-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: korifi-controllers-leader-election-role
subjects:
- kind: ServiceAccount
  name: korifi-controllers-controller-manager
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korifi-controllers-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korifi-controllers-manager-role
subjects:
- kind: ServiceAccount
  name: korifi-controllers-controller-manager
  namespace: {{ .Release.Namespace }}

{{- if .Values.jobTaskRunner.include }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korifi-job-task-runner-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korifi-job-task-runner-taskworkload-manager-role
subjects:
- kind: ServiceAccount
  name: korifi-controllers-controller-manager
  namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.kpackImageBuilder.include }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korifi-kpack-build-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korifi-kpack-build-manager-role
subjects:
- kind: ServiceAccount
  name: korifi-controllers-controller-manager
  namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.statefulsetRunner.include }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korifi-statefulset-runner-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korifi-statefulset-runner-appworkload-manager-role
subjects:
- kind: ServiceAccount
  name: korifi-controllers-controller-manager
  namespace: {{ .Release.Namespace }}
{{- end }}
