// Code generated by counterfeiter. DO NOT EDIT.
package apisfakes

import (
	"sync"

	"code.cloudfoundry.org/cf-k8s-api/apis"
	"code.cloudfoundry.org/cf-k8s-api/repositories"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type FakeCFDomainRepository struct {
	FetchDomainStub        func(client.Client, string) (repositories.DomainRecord, error)
	fetchDomainMutex       sync.RWMutex
	fetchDomainArgsForCall []struct {
		arg1 client.Client
		arg2 string
	}
	fetchDomainReturns struct {
		result1 repositories.DomainRecord
		result2 error
	}
	fetchDomainReturnsOnCall map[int]struct {
		result1 repositories.DomainRecord
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCFDomainRepository) FetchDomain(arg1 client.Client, arg2 string) (repositories.DomainRecord, error) {
	fake.fetchDomainMutex.Lock()
	ret, specificReturn := fake.fetchDomainReturnsOnCall[len(fake.fetchDomainArgsForCall)]
	fake.fetchDomainArgsForCall = append(fake.fetchDomainArgsForCall, struct {
		arg1 client.Client
		arg2 string
	}{arg1, arg2})
	stub := fake.FetchDomainStub
	fakeReturns := fake.fetchDomainReturns
	fake.recordInvocation("FetchDomain", []interface{}{arg1, arg2})
	fake.fetchDomainMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCFDomainRepository) FetchDomainCallCount() int {
	fake.fetchDomainMutex.RLock()
	defer fake.fetchDomainMutex.RUnlock()
	return len(fake.fetchDomainArgsForCall)
}

func (fake *FakeCFDomainRepository) FetchDomainCalls(stub func(client.Client, string) (repositories.DomainRecord, error)) {
	fake.fetchDomainMutex.Lock()
	defer fake.fetchDomainMutex.Unlock()
	fake.FetchDomainStub = stub
}

func (fake *FakeCFDomainRepository) FetchDomainArgsForCall(i int) (client.Client, string) {
	fake.fetchDomainMutex.RLock()
	defer fake.fetchDomainMutex.RUnlock()
	argsForCall := fake.fetchDomainArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCFDomainRepository) FetchDomainReturns(result1 repositories.DomainRecord, result2 error) {
	fake.fetchDomainMutex.Lock()
	defer fake.fetchDomainMutex.Unlock()
	fake.FetchDomainStub = nil
	fake.fetchDomainReturns = struct {
		result1 repositories.DomainRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeCFDomainRepository) FetchDomainReturnsOnCall(i int, result1 repositories.DomainRecord, result2 error) {
	fake.fetchDomainMutex.Lock()
	defer fake.fetchDomainMutex.Unlock()
	fake.FetchDomainStub = nil
	if fake.fetchDomainReturnsOnCall == nil {
		fake.fetchDomainReturnsOnCall = make(map[int]struct {
			result1 repositories.DomainRecord
			result2 error
		})
	}
	fake.fetchDomainReturnsOnCall[i] = struct {
		result1 repositories.DomainRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeCFDomainRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.fetchDomainMutex.RLock()
	defer fake.fetchDomainMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCFDomainRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ apis.CFDomainRepository = new(FakeCFDomainRepository)
