---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: cloudfoundry/korifi-api:latest
  path: .
  kubectlBuildkit:
    build:
      file: api/Dockerfile

- image: cloudfoundry/korifi-controllers:latest
  path: .
  kubectlBuildkit:
    build:
      file: controllers/Dockerfile

destinations:
- image: cloudfoundry/korifi-api:latest
  newImage: trinity.common.repositories.cloud.sap/trinity/korifi-api
- image: cloudfoundry/korifi-controllers:latest
  newImage: trinity.common.repositories.cloud.sap/trinity/korifi-controllers

