apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: cf-kpack-cluster-builder
spec:
  serviceAccountRef:
    name: kpack-service-account
    namespace: cf
  # Replace with real docker registry
  tag: gcr.io/cf-relint-greengrass/korifi/kpack/beta
  stack:
    name: cf-default-stack
    kind: ClusterStack
  store:
    name: cf-default-buildpacks
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/go
  - group:
    - id: paketo-buildpacks/nodejs
  - group:
      - id: paketo-buildpacks/ruby
  - group:
      - id: paketo-buildpacks/procfile
