name: Publish Helm Chart to gh-pages

on:
  release:
    types:
      - released  # Only on published releases (not drafts/prereleases)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-helm-chart:
    name: Publish Helm Chart to gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (default branch)
        uses: actions/checkout@v4

      - name: Download Helm chart .tgz from GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Release tag: $TAG_NAME"

          RELEASE_URL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/cloudfoundry/korifi/releases/latest | \
            jq -r '.assets[] | select(.name | endswith(".tgz")) | .browser_download_url')

          echo "Downloading: $RELEASE_URL"
          curl -L -H "Authorization: token $GITHUB_TOKEN" "$RELEASE_URL" -o chart.tgz

      - name: Unpack, patch Chart.yaml, and repackage
        run: |
          mkdir -p unpacked
          tar -xzf chart.tgz -C unpacked
      
          CHART_DIR=$(find unpacked -type d -name "korifi*")
          CHART_PATH="$CHART_DIR/Chart.yaml"
      
          # Determine release version from tag (if triggered by release), fallback to manual input
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            echo "Not triggered by a tag. Please set version manually for testing."
            VERSION="0.0.0-dev"  # fallback for manual run
          fi
      
          echo "Patching $CHART_PATH with version: $VERSION"
      
          yq e ".version = \"$VERSION\"" -i "$CHART_PATH"
          yq e ".appVersion = \"$VERSION\"" -i "$CHART_PATH"
      
          cat "$CHART_PATH"
      
          mkdir -p helm-repo
          helm package "$CHART_DIR" --destination helm-repo
          cd helm-repo
          helm repo index . --url https://vkazmin1.github.io/korifi
  

      - name: Repackage and index Helm chart
        run: |
          mkdir -p helm-repo
          helm package unpacked/** --destination helm-repo
          cd helm-repo
          helm repo index . --url https://vkazmin1.github.io/korifi

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy chart and index.yaml to gh-pages folder
        run: |
          cp -f helm-repo/* gh-pages/
          ls -l gh-pages

      - name: Commit and push to gh-pages
        working-directory: gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Publish Helm chart from release ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push origin gh-pages
