name: Publish Helm Chart to gh-pages

on:
  release:
    types:
      - released  # Ignores drafts and prereleases
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-helm-chart:
    name: Publish Helm Chart to gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Helm chart artifact from release
        uses: dsaltares/fetch-gh-release-asset@v1
        with:
          repo: cloudfoundry/korifi
          file: korifi-*.tgz
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ./chart.tgz

      - name: Unpack chart and index it
        run: |
          mkdir -p repo
          cp chart.tgz repo/
          cd repo
          helm repo index . --url https://cloudfoundry.github.io/korifi

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Copy updated chart and index.yaml
        run: |
          cp -r repo/* .

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Publish Helm chart from release ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push origin gh-pages
