name: Publish Helm Chart to gh-pages

on:
  release:
    types:
      - released  # Trigger only on real releases in vkazmin1/korifi
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-helm-chart:
    name: Publish Helm Chart to gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (default branch)
        uses: actions/checkout@v4

      - name: Download Helm chart .tgz from *this* GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Release tag: $TAG_NAME"

          RELEASE_URL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME | \
            jq -r '.assets[] | select(.name | endswith(".tgz")) | .browser_download_url')

          echo "Downloading: $RELEASE_URL"
          curl -L -H "Authorization: token $GITHUB_TOKEN" "$RELEASE_URL" -o chart.tgz

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Unpack, patch Chart.yaml, and repackage
        run: |
          mkdir -p unpacked
          tar -xzf chart.tgz -C unpacked

          CHART_DIR=$(find unpacked -type d -name "korifi*")
          CHART_PATH="$CHART_DIR/Chart.yaml"

          VERSION=${{ github.event.release.tag_name }}
          VERSION="${VERSION#v}"

          echo "Patching $CHART_PATH with version: $VERSION"
          yq e ".version = \"$VERSION\"" -i "$CHART_PATH"
          yq e ".appVersion = \"$VERSION\"" -i "$CHART_PATH"

          cat "$CHART_PATH"

          mkdir -p helm-repo
          helm package "$CHART_DIR" --destination helm-repo

          if [ -f gh-pages/index.yaml ]; then
            cp gh-pages/index.yaml helm-repo/index.yaml
            helm repo index helm-repo --url https://vkazmin1.github.io/korifi --merge index.yaml
          else
            helm repo index helm-repo --url https://vkazmin1.github.io/korifi
          fi

      - name: Copy chart and index.yaml to gh-pages folder
        run: |
          cp -f helm-repo/* gh-pages/
          ls -l gh-pages

      - name: Commit and push to gh-pages
        working-directory: gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Publish Helm chart from release ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push origin gh-pages
